### PR TITLE
waitFor considers errors whose message includes "timeout" retriable.

### PR DESCRIPTION
**Pull request by pwnall**
All tests (`gulp test`) pass for me locally.

At a high level, this seems reasonable, assuming that a timeout error might be caused by the fact that the condition we're checking for has not been met yet. Since we're willing to wait for the condition to become true, we should be willing to retry when a timeout happens.

Concretely, this patch is motivated by the need to stabilize a flaky test in our suite that fails due to a tough bug in ChromeDriver [1, 2, 3]. The failure mode is transient, so retrying fixes the flakiness.

[1] https://bugs.chromium.org/p/chromedriver/issues/detail?id=402
[2] https://bugs.chromium.org/p/chromedriver/issues/detail?id=817
[3]
http://stackoverflow.com/questions/34926866/selenium-chromedriver-timed-out-receiving-message-from-renderer-exception

### CODE REVIEW

**Comment by sebv** [comment]
@pwnall thx for the PRS, will have a look a bit later, doing the overdue trivial upgrade first.

**Comment by sebv** [comment]
That doesn't feel right to do this globally, alternative solution for this problem might be to wrap the asserters, so that they terminate on timeout, if it is the behavior needed.

**Comment by chadpaulson** [comment]
@admc This seems related to https://github.com/admc/wd/pull/501 and is the only thing preventing me from using mainline again.  Currently stuck between this bug, which is more crucial, and the inability to test with Firefox since mainline now supports the new geckodriver.  Would greatly appreciate if either of our PRs were merged.

**Comment by admc** [comment]
I'd be happy to resolve that! I have all your changes on a local branch and I get a number of Element failures. Firefox launches, but a number of element related operations fail. I tried with selenium 3.14 and 3.91 (which appears to be unreleased) and the latest geckodrive from brew. Let me know your thoughts.

**Pull request merged**
