### PR TITLE
[WIP][#555] Update request dependency

### PR DESCRIPTION
**Pull request by mattrayner**
* Fixed hinting issues

### CODE REVIEW

**Comment by mattrayner** [comment]
@admc I've updated the dependency to 2.88 and `npm test` passes - I've run `gulp test` but am getting some Firefox issues - I think they're related to my setup though, rather than actual test failures, I'd very much appreciate a steer from you? I'm not confident my machine is set up correctly :-1:

**Comment by mattrayner** [comment]
As an aside, the failing travis scripts seem to be related to a sauce connect issue

**Comment by admc** [comment]
Thanks for digging in. I'm actually getting an error running "gulp test-midway-chrome" - could you take a look? I also get firefox failing, and I think thats because something changed in the firefox driver with new versions of firefox, I would also love to get that fixed. The reason the branches are failing has to do with the shared secrets for running sauce connect on travis.. I don't know if there is a better way to do that now or not.

**Comment by mattrayner** [comment]
The Firefox issue might be related to this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1486909

**Comment by mattrayner** [comment]
The chrome issues seem to be related to calls to `Q.all`

**Comment by mattrayner** [comment]
@admc I've updated my PR with a fix for `gulp test-midway-chrome` - it includes some logging stuff which can be ignored - what would the impact be for removing calls to `Q.all`?

**Comment by mattrayner** [comment]
Regarding SauceConnect - it looks like it's free for open source https://saucelabs.com/open-source so it should be a case of creating an account and following the steps detailed in the travis docs
https://docs.travis-ci.com/user/gui-and-headless-browsers/

I'm not sure if this was originally set up and has broken over time? I *think* you need to be repo admin to add it to SauceLabs

**Comment by admc** [comment]
Thanks!

**Pull request merged**
