### PR TITLE
Fix test failures

### PR DESCRIPTION
**Pull request by joeyparrish**
This fixes linter errors, fixes tests broken by #521, and adds a note about getting chromedriver working.

### CODE REVIEW

**Comment by joeyparrish** [comment]
I found these issues while working on a PR for #495.  I thought it would be best to fix these pre-existing issues separately from any protocol-related changes.  Thanks!

**Comment by joeyparrish** [comment]
Also, JFYI, but your travis-CI config seems to be broken.  It fails to connect to Sauce Labs.  https://travis-ci.org/admc/wd/builds/385396124

I have run these tests locally on Linux and found everything passing except the "alt" key tests, which are skipped on Sauce and fail locally on Chrome in a way similar to what is described for Sauce.

**Comment by jlipps** [comment]
thanks for this and the other PRs @joeyparrish

**Comment by joeyparrish** [comment]
My pleasure!  Thanks for taking a look.

**Pull request merged**
