### PR TITLE
Added getCurrentPackage method

### PR DESCRIPTION
**Pull request by dpgraham**
(related to issue: https://github.com/appium/appium/issues/8674)

(@imurchie @jlipps)

### CODE REVIEW

**Comment by jlipps** [comment]
will need to update the docs too. either automatically (using `make`) or manually. i couldn't get the automatic one to work. see my last PR for where edits are required.

**Comment by dpgraham** [comment]
I just added the docs.

**Comment by dpgraham** [comment]
I don't have the ability to merge to admc/wd

**Comment by jlipps** [comment]
published in `1.4.0`

**Pull request merged**
