### PR TITLE
Updated packages and fixed tests

### PR DESCRIPTION
**Pull request by Havunen**
- Updated packages to latest versions, to reduce security issues reported by npm audit.
- Fixed tests (rejectUnAuthorized being true by default)
- Moved variable jsonData up one level as it was used inside the method.

Replaced 'spawn-mocha-parallel' package with 'gulp-spawn-mocha' as it does not seem to be maintained.

### CODE REVIEW

**Comment by Havunen** [comment]
Tests seem to pass, but its not connecting to Saucelabs, I guess SAUCE_USERNAME or ACCESSKEY is not set to process env correctly

**Comment by jlipps** [comment]
yeah, those env vars are secrets and therefore won't be set for jobs started b7 PRs for security reasons

**Comment by jlipps** [comment]
trying to run the tests locally with my own creds to see what happens

**Comment by jlipps** [comment]
Hi @Havunen sorry I didn't get to this earlier and now there are conflicts. Mind resolving and then I'll re-review?

**Comment by admc** [comment]
I took all these changes, ran the tests and just pushed in commit #b0405da33993263e69fd2af0a1402c42fa0ad4d2

Thanks again!

**Pull request closed without merging**
